// <auto-generated />
namespace AuffEventsMobileService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TeamMember_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamMember_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201412071305044_TeamMember_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
