// <auto-generated />
namespace AuffEventsApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class EventEntryFormTeamFKs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventEntryFormTeamFKs));
        
        string IMigrationMetadata.Id
        {
            get { return "201410132059266_Event-EntryForm-Team-FKs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
